name: CI

on: push

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir output
      - uses: maxheld83/pandoc@v2
        with:
          args: "--standalone -f markdown_github --output=output/resume.pdf README.md"
      - uses: actions/upload-artifact@master
        with:
          name: resume
          path: output/resume.pdf
