name: CI

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        run: mkdir docs
        with:
          args: |
            --output=docs/resume.pdf
            README.md
