name: CI

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir docs
      - uses: docker://pandoc/core:2.9
        with:
          args: |
            --output=docs/resume.pdf
            README.md
      - uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs
