name: "Build LaTex Document"

on:
  push:
    paths:
      - "src/**.tex"
jobs:
  build-and-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic -X build
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: build/resume/resume.pdf
