on:
  push:
    paths:
      - "**.tex"
      - "**.yml"
jobs:
  latex-job:
    runs-on: ubuntu-latest
    steps:
      - name: compile resume
        uses: actions/checkout@v2
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: run tectonic
        run: tectonic resume/resume.tex
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume/resume.pdf
