name: "Build Typst Resume"

on:
  push:
    branches:
      - master
    paths:
      - "resume.typ"
      - ".github/workflows/typst.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile resume
        run: typst compile resume.typ

      - name: Upload PDF to release
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
          tag_name: latest
          body: "Latest resume"

      - name: Create Pages artifact directory
        run: mkdir ./public

      - name: Move resume to public directory
        run: mv resume.pdf ./public

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
